# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/activmoveslist.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import custom_msg_python.msg

class activmoveslist(genpy.Message):
  _md5sum = "ad5a8f0f1484d74e62d785ee2bf5ef94"
  _type = "custom_msg_python/activmoveslist"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """custom_msg_python/actimove[] listing

================================================================================
MSG: custom_msg_python/actimove
custom_msg_python/blockdata block
float32 humanprio
float32 poscertainty
float32 stabilety

================================================================================
MSG: custom_msg_python/blockdata
int32 xlen
int32 ylen
int32 zlen

float32 xpos
float32 ypos
float32 zpos

int32 rotation

int32 blocktype
int32 blockcolor
"""
  __slots__ = ['listing']
  _slot_types = ['custom_msg_python/actimove[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       listing

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(activmoveslist, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.listing is None:
        self.listing = []
    else:
      self.listing = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.listing)
      buff.write(_struct_I.pack(length))
      for val1 in self.listing:
        _v1 = val1.block
        _x = _v1
        buff.write(_get_struct_3i3f3i().pack(_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.humanprio, _x.poscertainty, _x.stabilety))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.listing is None:
        self.listing = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.listing = []
      for i in range(0, length):
        val1 = custom_msg_python.msg.actimove()
        _v2 = val1.block
        _x = _v2
        start = end
        end += 36
        (_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor,) = _get_struct_3i3f3i().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.humanprio, _x.poscertainty, _x.stabilety,) = _get_struct_3f().unpack(str[start:end])
        self.listing.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.listing)
      buff.write(_struct_I.pack(length))
      for val1 in self.listing:
        _v3 = val1.block
        _x = _v3
        buff.write(_get_struct_3i3f3i().pack(_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.humanprio, _x.poscertainty, _x.stabilety))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.listing is None:
        self.listing = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.listing = []
      for i in range(0, length):
        val1 = custom_msg_python.msg.actimove()
        _v4 = val1.block
        _x = _v4
        start = end
        end += 36
        (_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor,) = _get_struct_3i3f3i().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.humanprio, _x.poscertainty, _x.stabilety,) = _get_struct_3f().unpack(str[start:end])
        self.listing.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_3i3f3i = None
def _get_struct_3i3f3i():
    global _struct_3i3f3i
    if _struct_3i3f3i is None:
        _struct_3i3f3i = struct.Struct("<3i3f3i")
    return _struct_3i3f3i
