# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/actimove.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import custom_msg_python.msg

class actimove(genpy.Message):
  _md5sum = "02dcd61482d1dd9838c30c59b919c3b8"
  _type = "custom_msg_python/actimove"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """custom_msg_python/blockdata block
float32 humanprio
float32 poscertainty
float32 stabilety

================================================================================
MSG: custom_msg_python/blockdata
int32 xlen
int32 ylen
int32 zlen

float32 xpos
float32 ypos
float32 zpos

int32 rotation

int32 blocktype
int32 blockcolor
"""
  __slots__ = ['block','humanprio','poscertainty','stabilety']
  _slot_types = ['custom_msg_python/blockdata','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       block,humanprio,poscertainty,stabilety

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(actimove, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.block is None:
        self.block = custom_msg_python.msg.blockdata()
      if self.humanprio is None:
        self.humanprio = 0.
      if self.poscertainty is None:
        self.poscertainty = 0.
      if self.stabilety is None:
        self.stabilety = 0.
    else:
      self.block = custom_msg_python.msg.blockdata()
      self.humanprio = 0.
      self.poscertainty = 0.
      self.stabilety = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i3f3i3f().pack(_x.block.xlen, _x.block.ylen, _x.block.zlen, _x.block.xpos, _x.block.ypos, _x.block.zpos, _x.block.rotation, _x.block.blocktype, _x.block.blockcolor, _x.humanprio, _x.poscertainty, _x.stabilety))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.block is None:
        self.block = custom_msg_python.msg.blockdata()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.block.xlen, _x.block.ylen, _x.block.zlen, _x.block.xpos, _x.block.ypos, _x.block.zpos, _x.block.rotation, _x.block.blocktype, _x.block.blockcolor, _x.humanprio, _x.poscertainty, _x.stabilety,) = _get_struct_3i3f3i3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i3f3i3f().pack(_x.block.xlen, _x.block.ylen, _x.block.zlen, _x.block.xpos, _x.block.ypos, _x.block.zpos, _x.block.rotation, _x.block.blocktype, _x.block.blockcolor, _x.humanprio, _x.poscertainty, _x.stabilety))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.block is None:
        self.block = custom_msg_python.msg.blockdata()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.block.xlen, _x.block.ylen, _x.block.zlen, _x.block.xpos, _x.block.ypos, _x.block.zpos, _x.block.rotation, _x.block.blocktype, _x.block.blockcolor, _x.humanprio, _x.poscertainty, _x.stabilety,) = _get_struct_3i3f3i3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i3f3i3f = None
def _get_struct_3i3f3i3f():
    global _struct_3i3f3i3f
    if _struct_3i3f3i3f is None:
        _struct_3i3f3i3f = struct.Struct("<3i3f3i3f")
    return _struct_3i3f3i3f
