# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/allbrickslist.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class allbrickslist(genpy.Message):
  _md5sum = "8ba9bb7706e119d01cad46b2d7444f29"
  _type = "custom_msg_python/allbrickslist"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose2D[] red_small
geometry_msgs/Pose2D[] red_large
geometry_msgs/Pose2D[] blue_small
geometry_msgs/Pose2D[] blue_large
geometry_msgs/Pose2D[] yelow_small
geometry_msgs/Pose2D[] yelow_large

geometry_msgs/Point[] red_small_3d
geometry_msgs/Point[] red_large_3d
geometry_msgs/Point[] blue_small_3d
geometry_msgs/Point[] blue_large_3d
geometry_msgs/Point[] yelow_small_3d
geometry_msgs/Point[] yelow_large_3d

================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['red_small','red_large','blue_small','blue_large','yelow_small','yelow_large','red_small_3d','red_large_3d','blue_small_3d','blue_large_3d','yelow_small_3d','yelow_large_3d']
  _slot_types = ['geometry_msgs/Pose2D[]','geometry_msgs/Pose2D[]','geometry_msgs/Pose2D[]','geometry_msgs/Pose2D[]','geometry_msgs/Pose2D[]','geometry_msgs/Pose2D[]','geometry_msgs/Point[]','geometry_msgs/Point[]','geometry_msgs/Point[]','geometry_msgs/Point[]','geometry_msgs/Point[]','geometry_msgs/Point[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       red_small,red_large,blue_small,blue_large,yelow_small,yelow_large,red_small_3d,red_large_3d,blue_small_3d,blue_large_3d,yelow_small_3d,yelow_large_3d

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(allbrickslist, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.red_small is None:
        self.red_small = []
      if self.red_large is None:
        self.red_large = []
      if self.blue_small is None:
        self.blue_small = []
      if self.blue_large is None:
        self.blue_large = []
      if self.yelow_small is None:
        self.yelow_small = []
      if self.yelow_large is None:
        self.yelow_large = []
      if self.red_small_3d is None:
        self.red_small_3d = []
      if self.red_large_3d is None:
        self.red_large_3d = []
      if self.blue_small_3d is None:
        self.blue_small_3d = []
      if self.blue_large_3d is None:
        self.blue_large_3d = []
      if self.yelow_small_3d is None:
        self.yelow_small_3d = []
      if self.yelow_large_3d is None:
        self.yelow_large_3d = []
    else:
      self.red_small = []
      self.red_large = []
      self.blue_small = []
      self.blue_large = []
      self.yelow_small = []
      self.yelow_large = []
      self.red_small_3d = []
      self.red_large_3d = []
      self.blue_small_3d = []
      self.blue_large_3d = []
      self.yelow_small_3d = []
      self.yelow_large_3d = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.red_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.red_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.blue_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.blue_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.yelow_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.yelow_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.red_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.red_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.blue_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.blue_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.yelow_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.yelow_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.red_small is None:
        self.red_small = None
      if self.red_large is None:
        self.red_large = None
      if self.blue_small is None:
        self.blue_small = None
      if self.blue_large is None:
        self.blue_large = None
      if self.yelow_small is None:
        self.yelow_small = None
      if self.yelow_large is None:
        self.yelow_large = None
      if self.red_small_3d is None:
        self.red_small_3d = None
      if self.red_large_3d is None:
        self.red_large_3d = None
      if self.blue_small_3d is None:
        self.blue_small_3d = None
      if self.blue_large_3d is None:
        self.blue_large_3d = None
      if self.yelow_small_3d is None:
        self.yelow_small_3d = None
      if self.yelow_large_3d is None:
        self.yelow_large_3d = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.red_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.red_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.blue_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.blue_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.red_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.red_large_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.blue_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.blue_large_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_large_3d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.red_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.red_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.blue_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.blue_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.yelow_small)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_small:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.yelow_large)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_large:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.red_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.red_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.red_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.blue_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.blue_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.blue_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.yelow_small_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_small_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.yelow_large_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.yelow_large_3d:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.red_small is None:
        self.red_small = None
      if self.red_large is None:
        self.red_large = None
      if self.blue_small is None:
        self.blue_small = None
      if self.blue_large is None:
        self.blue_large = None
      if self.yelow_small is None:
        self.yelow_small = None
      if self.yelow_large is None:
        self.yelow_large = None
      if self.red_small_3d is None:
        self.red_small_3d = None
      if self.red_large_3d is None:
        self.red_large_3d = None
      if self.blue_small_3d is None:
        self.blue_small_3d = None
      if self.blue_large_3d is None:
        self.blue_large_3d = None
      if self.yelow_small_3d is None:
        self.yelow_small_3d = None
      if self.yelow_large_3d is None:
        self.yelow_large_3d = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.red_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.red_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.blue_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.blue_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_small = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_small.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_large = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_large.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.red_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.red_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.red_large_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.blue_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.blue_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.blue_large_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_small_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_small_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.yelow_large_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.yelow_large_3d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
