# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/blockdata.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class blockdata(genpy.Message):
  _md5sum = "eac9cc71fe8df90f9f784800602aae10"
  _type = "custom_msg_python/blockdata"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 xlen
int32 ylen
int32 zlen

float32 xpos
float32 ypos
float32 zpos

int32 rotation

int32 blocktype
int32 blockcolor
"""
  __slots__ = ['xlen','ylen','zlen','xpos','ypos','zpos','rotation','blocktype','blockcolor']
  _slot_types = ['int32','int32','int32','float32','float32','float32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xlen,ylen,zlen,xpos,ypos,zpos,rotation,blocktype,blockcolor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(blockdata, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.xlen is None:
        self.xlen = 0
      if self.ylen is None:
        self.ylen = 0
      if self.zlen is None:
        self.zlen = 0
      if self.xpos is None:
        self.xpos = 0.
      if self.ypos is None:
        self.ypos = 0.
      if self.zpos is None:
        self.zpos = 0.
      if self.rotation is None:
        self.rotation = 0
      if self.blocktype is None:
        self.blocktype = 0
      if self.blockcolor is None:
        self.blockcolor = 0
    else:
      self.xlen = 0
      self.ylen = 0
      self.zlen = 0
      self.xpos = 0.
      self.ypos = 0.
      self.zpos = 0.
      self.rotation = 0
      self.blocktype = 0
      self.blockcolor = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i3f3i().pack(_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor,) = _get_struct_3i3f3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i3f3i().pack(_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.xlen, _x.ylen, _x.zlen, _x.xpos, _x.ypos, _x.zpos, _x.rotation, _x.blocktype, _x.blockcolor,) = _get_struct_3i3f3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i3f3i = None
def _get_struct_3i3f3i():
    global _struct_3i3f3i
    if _struct_3i3f3i is None:
        _struct_3i3f3i = struct.Struct("<3i3f3i")
    return _struct_3i3f3i
