# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/custom2.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class custom2(genpy.Message):
  _md5sum = "42115633ead9253039212ba53419851b"
  _type = "custom_msg_python/custom2"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point handposition
geometry_msgs/Point handvelocity
geometry_msgs/Point armposition
geometry_msgs/Point armvelocity
float32 time


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['handposition','handvelocity','armposition','armvelocity','time']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       handposition,handvelocity,armposition,armvelocity,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(custom2, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.handposition is None:
        self.handposition = geometry_msgs.msg.Point()
      if self.handvelocity is None:
        self.handvelocity = geometry_msgs.msg.Point()
      if self.armposition is None:
        self.armposition = geometry_msgs.msg.Point()
      if self.armvelocity is None:
        self.armvelocity = geometry_msgs.msg.Point()
      if self.time is None:
        self.time = 0.
    else:
      self.handposition = geometry_msgs.msg.Point()
      self.handvelocity = geometry_msgs.msg.Point()
      self.armposition = geometry_msgs.msg.Point()
      self.armvelocity = geometry_msgs.msg.Point()
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12df().pack(_x.handposition.x, _x.handposition.y, _x.handposition.z, _x.handvelocity.x, _x.handvelocity.y, _x.handvelocity.z, _x.armposition.x, _x.armposition.y, _x.armposition.z, _x.armvelocity.x, _x.armvelocity.y, _x.armvelocity.z, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.handposition is None:
        self.handposition = geometry_msgs.msg.Point()
      if self.handvelocity is None:
        self.handvelocity = geometry_msgs.msg.Point()
      if self.armposition is None:
        self.armposition = geometry_msgs.msg.Point()
      if self.armvelocity is None:
        self.armvelocity = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 100
      (_x.handposition.x, _x.handposition.y, _x.handposition.z, _x.handvelocity.x, _x.handvelocity.y, _x.handvelocity.z, _x.armposition.x, _x.armposition.y, _x.armposition.z, _x.armvelocity.x, _x.armvelocity.y, _x.armvelocity.z, _x.time,) = _get_struct_12df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12df().pack(_x.handposition.x, _x.handposition.y, _x.handposition.z, _x.handvelocity.x, _x.handvelocity.y, _x.handvelocity.z, _x.armposition.x, _x.armposition.y, _x.armposition.z, _x.armvelocity.x, _x.armvelocity.y, _x.armvelocity.z, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.handposition is None:
        self.handposition = geometry_msgs.msg.Point()
      if self.handvelocity is None:
        self.handvelocity = geometry_msgs.msg.Point()
      if self.armposition is None:
        self.armposition = geometry_msgs.msg.Point()
      if self.armvelocity is None:
        self.armvelocity = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 100
      (_x.handposition.x, _x.handposition.y, _x.handposition.z, _x.handvelocity.x, _x.handvelocity.y, _x.handvelocity.z, _x.armposition.x, _x.armposition.y, _x.armposition.z, _x.armvelocity.x, _x.armvelocity.y, _x.armvelocity.z, _x.time,) = _get_struct_12df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12df = None
def _get_struct_12df():
    global _struct_12df
    if _struct_12df is None:
        _struct_12df = struct.Struct("<12df")
    return _struct_12df
