# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/custom1.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class custom1(genpy.Message):
  _md5sum = "31d9aef80e7e38c1513be9d4decd01d5"
  _type = "custom_msg_python/custom1"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x
float32 y
float32 z

float32 e1
float32 e2
float32 e3
float32 e4

float32 velocity
float32 acceleration
bool priority
"""
  __slots__ = ['x','y','z','e1','e2','e3','e4','velocity','acceleration','priority']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,e1,e2,e3,e4,velocity,acceleration,priority

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(custom1, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.e1 is None:
        self.e1 = 0.
      if self.e2 is None:
        self.e2 = 0.
      if self.e3 is None:
        self.e3 = 0.
      if self.e4 is None:
        self.e4 = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.acceleration is None:
        self.acceleration = 0.
      if self.priority is None:
        self.priority = False
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.e1 = 0.
      self.e2 = 0.
      self.e3 = 0.
      self.e4 = 0.
      self.velocity = 0.
      self.acceleration = 0.
      self.priority = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9fB().pack(_x.x, _x.y, _x.z, _x.e1, _x.e2, _x.e3, _x.e4, _x.velocity, _x.acceleration, _x.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 37
      (_x.x, _x.y, _x.z, _x.e1, _x.e2, _x.e3, _x.e4, _x.velocity, _x.acceleration, _x.priority,) = _get_struct_9fB().unpack(str[start:end])
      self.priority = bool(self.priority)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9fB().pack(_x.x, _x.y, _x.z, _x.e1, _x.e2, _x.e3, _x.e4, _x.velocity, _x.acceleration, _x.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 37
      (_x.x, _x.y, _x.z, _x.e1, _x.e2, _x.e3, _x.e4, _x.velocity, _x.acceleration, _x.priority,) = _get_struct_9fB().unpack(str[start:end])
      self.priority = bool(self.priority)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9fB = None
def _get_struct_9fB():
    global _struct_9fB
    if _struct_9fB is None:
        _struct_9fB = struct.Struct("<9fB")
    return _struct_9fB
