// Generated by gencpp from file custom_msg_python/allbrickslist.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PYTHON_MESSAGE_ALLBRICKSLIST_H
#define CUSTOM_MSG_PYTHON_MESSAGE_ALLBRICKSLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace custom_msg_python
{
template <class ContainerAllocator>
struct allbrickslist_
{
  typedef allbrickslist_<ContainerAllocator> Type;

  allbrickslist_()
    : red_small()
    , red_large()
    , blue_small()
    , blue_large()
    , yelow_small()
    , yelow_large()
    , red_small_3d()
    , red_large_3d()
    , blue_small_3d()
    , blue_large_3d()
    , yelow_small_3d()
    , yelow_large_3d()  {
    }
  allbrickslist_(const ContainerAllocator& _alloc)
    : red_small(_alloc)
    , red_large(_alloc)
    , blue_small(_alloc)
    , blue_large(_alloc)
    , yelow_small(_alloc)
    , yelow_large(_alloc)
    , red_small_3d(_alloc)
    , red_large_3d(_alloc)
    , blue_small_3d(_alloc)
    , blue_large_3d(_alloc)
    , yelow_small_3d(_alloc)
    , yelow_large_3d(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _red_small_type;
  _red_small_type red_small;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _red_large_type;
  _red_large_type red_large;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _blue_small_type;
  _blue_small_type blue_small;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _blue_large_type;
  _blue_large_type blue_large;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _yelow_small_type;
  _yelow_small_type yelow_small;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _yelow_large_type;
  _yelow_large_type yelow_large;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _red_small_3d_type;
  _red_small_3d_type red_small_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _red_large_3d_type;
  _red_large_3d_type red_large_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _blue_small_3d_type;
  _blue_small_3d_type blue_small_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _blue_large_3d_type;
  _blue_large_3d_type blue_large_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _yelow_small_3d_type;
  _yelow_small_3d_type yelow_small_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _yelow_large_3d_type;
  _yelow_large_3d_type yelow_large_3d;





  typedef boost::shared_ptr< ::custom_msg_python::allbrickslist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_python::allbrickslist_<ContainerAllocator> const> ConstPtr;

}; // struct allbrickslist_

typedef ::custom_msg_python::allbrickslist_<std::allocator<void> > allbrickslist;

typedef boost::shared_ptr< ::custom_msg_python::allbrickslist > allbrickslistPtr;
typedef boost::shared_ptr< ::custom_msg_python::allbrickslist const> allbrickslistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_python::allbrickslist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_python::allbrickslist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg_python::allbrickslist_<ContainerAllocator1> & lhs, const ::custom_msg_python::allbrickslist_<ContainerAllocator2> & rhs)
{
  return lhs.red_small == rhs.red_small &&
    lhs.red_large == rhs.red_large &&
    lhs.blue_small == rhs.blue_small &&
    lhs.blue_large == rhs.blue_large &&
    lhs.yelow_small == rhs.yelow_small &&
    lhs.yelow_large == rhs.yelow_large &&
    lhs.red_small_3d == rhs.red_small_3d &&
    lhs.red_large_3d == rhs.red_large_3d &&
    lhs.blue_small_3d == rhs.blue_small_3d &&
    lhs.blue_large_3d == rhs.blue_large_3d &&
    lhs.yelow_small_3d == rhs.yelow_small_3d &&
    lhs.yelow_large_3d == rhs.yelow_large_3d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg_python::allbrickslist_<ContainerAllocator1> & lhs, const ::custom_msg_python::allbrickslist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_python::allbrickslist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_python::allbrickslist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_python::allbrickslist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ba9bb7706e119d01cad46b2d7444f29";
  }

  static const char* value(const ::custom_msg_python::allbrickslist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ba9bb7706e119d0ULL;
  static const uint64_t static_value2 = 0x1cad46b2d7444f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_python/allbrickslist";
  }

  static const char* value(const ::custom_msg_python::allbrickslist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] red_small\n"
"geometry_msgs/Pose2D[] red_large\n"
"geometry_msgs/Pose2D[] blue_small\n"
"geometry_msgs/Pose2D[] blue_large\n"
"geometry_msgs/Pose2D[] yelow_small\n"
"geometry_msgs/Pose2D[] yelow_large\n"
"\n"
"geometry_msgs/Point[] red_small_3d\n"
"geometry_msgs/Point[] red_large_3d\n"
"geometry_msgs/Point[] blue_small_3d\n"
"geometry_msgs/Point[] blue_large_3d\n"
"geometry_msgs/Point[] yelow_small_3d\n"
"geometry_msgs/Point[] yelow_large_3d\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msg_python::allbrickslist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red_small);
      stream.next(m.red_large);
      stream.next(m.blue_small);
      stream.next(m.blue_large);
      stream.next(m.yelow_small);
      stream.next(m.yelow_large);
      stream.next(m.red_small_3d);
      stream.next(m.red_large_3d);
      stream.next(m.blue_small_3d);
      stream.next(m.blue_large_3d);
      stream.next(m.yelow_small_3d);
      stream.next(m.yelow_large_3d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct allbrickslist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_python::allbrickslist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_python::allbrickslist_<ContainerAllocator>& v)
  {
    s << indent << "red_small[]" << std::endl;
    for (size_t i = 0; i < v.red_small.size(); ++i)
    {
      s << indent << "  red_small[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.red_small[i]);
    }
    s << indent << "red_large[]" << std::endl;
    for (size_t i = 0; i < v.red_large.size(); ++i)
    {
      s << indent << "  red_large[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.red_large[i]);
    }
    s << indent << "blue_small[]" << std::endl;
    for (size_t i = 0; i < v.blue_small.size(); ++i)
    {
      s << indent << "  blue_small[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.blue_small[i]);
    }
    s << indent << "blue_large[]" << std::endl;
    for (size_t i = 0; i < v.blue_large.size(); ++i)
    {
      s << indent << "  blue_large[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.blue_large[i]);
    }
    s << indent << "yelow_small[]" << std::endl;
    for (size_t i = 0; i < v.yelow_small.size(); ++i)
    {
      s << indent << "  yelow_small[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.yelow_small[i]);
    }
    s << indent << "yelow_large[]" << std::endl;
    for (size_t i = 0; i < v.yelow_large.size(); ++i)
    {
      s << indent << "  yelow_large[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.yelow_large[i]);
    }
    s << indent << "red_small_3d[]" << std::endl;
    for (size_t i = 0; i < v.red_small_3d.size(); ++i)
    {
      s << indent << "  red_small_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.red_small_3d[i]);
    }
    s << indent << "red_large_3d[]" << std::endl;
    for (size_t i = 0; i < v.red_large_3d.size(); ++i)
    {
      s << indent << "  red_large_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.red_large_3d[i]);
    }
    s << indent << "blue_small_3d[]" << std::endl;
    for (size_t i = 0; i < v.blue_small_3d.size(); ++i)
    {
      s << indent << "  blue_small_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.blue_small_3d[i]);
    }
    s << indent << "blue_large_3d[]" << std::endl;
    for (size_t i = 0; i < v.blue_large_3d.size(); ++i)
    {
      s << indent << "  blue_large_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.blue_large_3d[i]);
    }
    s << indent << "yelow_small_3d[]" << std::endl;
    for (size_t i = 0; i < v.yelow_small_3d.size(); ++i)
    {
      s << indent << "  yelow_small_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.yelow_small_3d[i]);
    }
    s << indent << "yelow_large_3d[]" << std::endl;
    for (size_t i = 0; i < v.yelow_large_3d.size(); ++i)
    {
      s << indent << "  yelow_large_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.yelow_large_3d[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_PYTHON_MESSAGE_ALLBRICKSLIST_H
